<td><input type="text" class="form-control" name="qty_youth_xs[]" value="{{order_line['qty_youth_xs']}}"></td>
<td><input type="text" class="form-control" name="qty_youth_s[]" value="{{order_line['qty_youth_s']}}"></td>
<td><input type="text" class="form-control" name="qty_youth_m[]" value="{{order_line['qty_youth_m']}}"></td>
<td><input type="text" class="form-control" name="qty_youth_l[]" value="{{order_line['qty_youth_l']}}"></td>
<td><input type="text" class="form-control" name="qty_youth_xl[]" value="{{order_line['qty_youth_xl']}}"></td>
<td><input type="text" class="form-control" name="qty_adult_xs[]" value="{{order_line['qty_adult_xs']}}"></td>
<td><input type="text" class="form-control" name="qty_adult_s[]" value="{{order_line['qty_adult_s']}}"></td>
<td><input type="text" class="form-control" name="qty_adult_m[]" value="{{order_line['qty_adult_m']}}"></td>
<td><input type="text" class="form-control" name="qty_adult_l[]" value="{{order_line['qty_adult_l']}}"></td>
<td><input type="text" class="form-control" name="qty_adult_xl[]" value="{{order_line['qty_adult_xl']}}"></td>
<td><input type="text" class="form-control" name="qty_adult_2xl[]" value="{{order_line['qty_adult_2xl']}}"></td>
<td><input type="text" class="form-control" name="qty_adult_3xl[]" value="{{order_line['qty_adult_3xl']}}"></td>
<td><input type="text" class="form-control" name="qty_adult_4xl[]" value="{{order_line['qty_adult_4xl']}}"></td>
<td><input type="text" class="form-control" name="qty_adult_5xl[]" value="{{order_line['qty_adult_5xl']}}"></td>
<td><input type="text" class="form-control" name="qty_adult_6xl[]" value="{{order_line['qty_adult_6xl']}}"></td>